### ISSUE TITLE
HowTo rebase with iojs, and/or node.

### ISSUE THREAD

**Issue by jaredallard** [nwjs/node#2]
Hi, I wanted to know if there is a simple way of rebasing with the latest version of iojs and etc as I want to merge iojs 1.6.3 into my own build of nw.

**Comment by ghostoy** [comment]
I tried to build with official node.js 0.12. My experience is to cherry pick all patches onto your own version.

**Comment by RainbowDashDC** [comment]
@ghostoy Is there a method easier than just manually inserting said changes?

**Comment by ghostoy** [comment]
I dont know. But seems it's impossible because code changes all the time. You have to resolve conflicts manually.
