### ISSUE TITLE
[nw13] alpha5: https is not working

### ISSUE THREAD

**Issue by andresiraola** [nwjs/node#3]
The "http" module loads and works correclty (so far) but I cannot use "https". 

I try to load it by doing:
```javascript
var https = nw.require('https');
```
but I get a blank page and devtools doesn't show up when I press F12.

It seems like some kind of deadlock when node is trying to load the module.

Did you have the same problem? Is there a temporary workaround? How can I help you to fix it? Do you have an idea of what can be the issue here?

Thanks!

**Comment by rogerwang** [comment]
Thanks for reporting. This is just fixed in git. Will be available in the next alpha release or live build.
