### ISSUE TITLE
invalid preprocessor command 'include_next'

### ISSUE THREAD

**Issue by KanomiDim** [nwjs/node#41]
Hello.

I'm trying to compile node, after going through "Building NWJS" guide, at:
http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js

I managed to compile the nwjs smoothly, but i'm running into some issue when trying to execute:
ninja -C out/Release node

same goes for:
ninja -C out/Release_x64 node
ninja -C out/Debug node
ninja -C out/Debug_x64 node

(getting the exact error)

(Using nw46 branch)

full message in the console:

$ ninja -C out/Release_x64 node
ninja: Entering directory `out/Release_x64'
[1/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.detect-wakeup.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.detect-wakeup.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.detect-wakeup.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\detect-wakeup.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.detect-wakeup.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[2/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.inet.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.inet.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.inet.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\inet.c /Foobj\third_party\node-nw\deps\uv\src\libuv.inet.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\stdio.h(107): fatal error C1021: invalid preprocessor command 'include_next'
[3/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.error.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.error.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.error.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\error.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.error.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[4/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.timer.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.timer.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.timer.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\timer.c /Foobj\third_party\node-nw\deps\uv\src\libuv.timer.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[5/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.random.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.random.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.random.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\random.c /Foobj\third_party\node-nw\deps\uv\src\libuv.random.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[6/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.uv-common.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.uv-common.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.uv-common.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\uv-common.c /Foobj\third_party\node-nw\deps\uv\src\libuv.uv-common.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[7/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.dl.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.dl.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.dl.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\dl.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.dl.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[8/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.idna.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.idna.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.idna.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\idna.c /Foobj\third_party\node-nw\deps\uv\src\libuv.idna.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[9/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.core.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.core.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.core.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\core.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.core.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[10/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.fs.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.fs.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.fs.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\fs.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.fs.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\stdlib.h(97): fatal error C1021: invalid preprocessor command 'include_next'
[11/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.fs-event.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.fs-event.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.fs-event.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\fs-event.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.fs-event.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[12/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.version.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.version.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.version.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\version.c /Foobj\third_party\node-nw\deps\uv\src\libuv.version.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[13/1388] CC obj\third_party\node-nw\deps\uv\src\libuv.fs-poll.obj
FAILED: obj/third_party/node-nw/deps/uv/src/libuv.fs-poll.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\libuv.fs-poll.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\fs-poll.c /Foobj\third_party\node-nw\deps\uv\src\libuv.fs-poll.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
[14/1388] CC obj\third_party\node-nw\deps\uv\src\win\libuv.async.obj
FAILED: obj/third_party/node-nw/deps/uv/src/win/libuv.async.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe" /nologo /showIncludes /FC @obj\third_party\node-nw\deps\uv\src\win\libuv.async.obj.rsp /c ..\..\third_party\node-nw\deps\uv\src\win\async.c /Foobj\third_party\node-nw\deps\uv\src\win\libuv.async.obj /Fdobj\third_party\node-nw\deps\uv\libuv.c.pdb
cl : Command line warning D9002 : ignoring unknown option '/Zc:dllexportInlines-'
C:\kanomi\nwjs464\src\buildtools\third_party\libc++\trunk\include\errno.h(31): fatal error C1021: invalid preprocessor command 'include_next'
ninja: build stopped: subcommand failed.

Did anyone run into this issue?

Thanks!

**Comment by rogerwang** [comment]
It's building with cl.exe, that's why it failed. Now the Node is built with clang, so you'll need to config the build properly. See how the official build is configured here: http://buildbot-master.nwjs.io:8010/builders/nw46_sdk_win64/builds/27/steps/node_gyp/logs/stdio
