### ISSUE TITLE
could not open '../nw/libc++.dll.lib'

### ISSUE THREAD

**Issue by KanomiDim** [nwjs/node#42]
Hello.

I'm trying to build nwjs46 for my first time. (Windows 10 x64)

I've managed to compile nwjs after going through "Building NWJS" guide, at:
http://docs.nwjs.io/en/latest/For%20Developers/Building%20NW.js

But when i tried to compile the node, i got the following error:

$ ninja -C out/Release_x64 node
ninja: Entering directory `out/Release_x64'
[1/99] LINK_EMBED(DLL) icuuc.dll
FAILED: icuuc.dll icuuc.dll.lib icuuc.dll.pdb
C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True icuuc.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False ..\..\third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:icuuc.dll.lib /DLL /OUT:icuuc.dll @icuuc.dll.rsp" 2 mt.exe rc.exe "obj\third_party\icu\icuuc.icuuc.dll.intermediate.manifest" obj\third_party\icu\icuuc.icuuc.dll.generated.manifest
lld-link: error: could not open '../nw/libc++.dll.lib': no such file or directory
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False ..\..\third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo /IMPLIB:icuuc.dll.lib /DLL /OUT:icuuc.dll @icuuc.dll.rsp icuuc.dll.manifest.res' returned non-zero exit status 1
ninja: build stopped: subcommand failed.

I've tried some things to resolve this issue, such as downloading and installing LLVM 10 from the link:
https://releases.llvm.org/download.html#10.0.0

I would appretiate assist with the following.

Thanks.

**Comment by KanomiDim** [comment]
I have potentially found the issue.

The issue was that for some reason there were made some changes to icu.gyp. After discarding those changes, the problem seems to be passed.

Attached an image showing the case.

![461e9d30-a08d-42f8-a106-70299640aa83](https://user-images.githubusercontent.com/68009729/87951359-24952e00-cab1-11ea-8067-80a1ce74a129.jpg)


Can anyone approve that it is fine thing to do?


Thanks!

**Comment by rogerwang** [comment]
This is not an issue. 
Please ask questions in our mailing list: https://groups.google.com/forum/#!forum/nwjs-general

**Comment by rogerwang** [comment]
It looks like you are building Node with `component='shared_library'`, which is for debug mode.
