### ISSUE TITLE
Update "print sys.byteorder" (Python compatibility issue)

### ISSUE THREAD

**Issue by corwin-of-amber** [nwjs/node#46]
This line:
https://github.com/nwjs/node/blob/d168d6d2f33b9f824b7ff4edd4850dad7da250bd/common.gypi#L65

Works if the default Python is 2.x, fails in 3.x. Unlike other invocations of `python` in gyp, it is not affected by setting e.g. `--python` (https://github.com/nwjs/nw-gyp/issues/122).

This was already patched in upstream Node (https://github.com/nodejs/node/commit/3d8b844112bf6526ce126ecaec85f83b31a0a9aa) to:
```
    'v8_host_byteorder': '<!(python -c "import sys; print(sys.byteorder)")',
```

Though this is in `toolchain.gypi`; couldn't find their `common.gypi`. At any rate, seems to be worth it to make this small fix; this currently breaks `nw-gyp`, which admittedly does not have many users, but it comes in handy once in a while.

**Comment by corwin-of-amber** [comment]
Is there a chance to get this small fix in NWjs?

**Comment by tharatau** [comment]
@corwin-of-amber I've made a PR for this. Could you elaborate how this breaks `nw-gyp`?

**Comment by corwin-of-amber** [comment]
Wow, I seriously don't remember all the details but this file is somehow installed and is loaded by gyp. I think this is independent of which Python is used by node-gyp; but in 2023 (even 2020) it is unreasonable to assume that the default system Python is Python 2.x. `<!(..)` just invokes a shell command. This assumption means that 99% of the users will not be able to use nw-gyp without tampering with their PATH to make Python 2.x occur first.
