### ISSUE TITLE
nw80 branch not created

### ISSUE THREAD

**Issue by ayushmanchhabra** [nwjs/node#56]
[nw-patches](https://github.com/nwutils/nw-patches) repo assumes that for every release, there is a corresponding NW.js branch. Our GitHub Action failed to generated a [`node.patch`](https://github.com/nwutils/nw-patches/blob/main/patches/node.patch) file since a `nw80` branch has not been created. Would like to request to create a branch for `nw80`. Thanks!

**Comment by rogerwang** [comment]
Thanks. It's fixed.
